jobs:
# - job: macOS
#   displayName: macos-latest
#   pool:
#     vmImage: 'macos-latest'
#   strategy:
#     matrix:
#       Python37:
#         python.version: '3.7'
#       Python38:
#         python.version: '3.8'
#       Python39:
#         python.version: '3.9'
#       Python310:
#         python.version: '3.10'
#
#   steps:
#   - bash: echo "##vso[task.prependpath]$CONDA/bin"
#     displayName: Add conda to PATH
#
#   - bash: sudo chown -R $USER $CONDA
#     displayName: Take ownership of conda installation
#
#   - bash: |
#       conda config --add channels conda-forge
#       conda config --set always_yes yes
#       conda install -n root conda-build numpy fftw
#     displayName: Set up Anaconda
#
#   - bash: |
#       conda build --python $PYTHON_VERSION ./conf
#     displayName: Build and test

- job: Ubuntu
  displayName: Ubuntu
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python37:
        python.version: '3.7'
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: |
      conda config --add channels conda-forge
      conda config --set always_yes yes
      conda install -n root mpi4py mpich numpy fftw
    displayName: Set up Anaconda

  - bash: |
      conda create --name mpi4py_fft_env \
        python=$PYTHON_VERSION \
        numpy fftw mpi4py mpich \
        pyfftw=0.12 scipy coverage
      source activate mpi4py_fft_env
      pip install -vvv --no-deps .
      pip install codecov
      cd tests && ./runtests.sh
    displayName: Build and test

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - bash: |
      if [ $PYTHON_VERSION == 3.8 ]; then
        source activate mpi4py_fft_env
        cd tests
        coverage xml -o ./coverage.xml
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -f coverage.xml
      fi
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Upload to Codecov
