---
name: "Setup FFTW"
description: "Set up FFTW."
author: "Ben Landrum"
inputs:
  os:
    description: "Hyphenated operating system name, e.g., ubuntu-latest."
outputs:
  include-dir:
    description: "The installed FFTW include directory."
    value: ${{ steps.setup-fftw.outputs.include-dir }}
  library-dir:
    description: "The installed FFTW library directory."
    value: ${{ steps.setup-fftw.outputs.library-dir }}
runs:
  using: "composite"
  steps:
    - id: setup-fftw
      run: ${GITHUB_ACTION_PATH}/setup-fftw.sh ${{ inputs.os }}
      shell: bash
