name: github-CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        mpi:
          - mpich
          - openmpi
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12-dev"

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - run: |
        # Install fftw
        case $(uname) in
          Linux)
          sudo apt update && sudo apt install -y -q fftw-dev
            ;;
          Darwin)
            brew install fftw
            ;;
        esac

    - run: python -m pip install -U pip build

    - run: python -m pip install -r requirements.txt

    - run: python -m build

    - uses: mpi4py/setup-mpi@v1
      with:
        mpi: ${{ matrix.mpi }}

    - run: pip install -vvv dist/mpi4py_fft-*.whl
